### ISSUE TITLE
Dialog Simplify Error(s)

### ISSUE THREAD

**Issue by Shivanshu-Gupta** [telepathylabsai/OpenDF#2]
Hi, I am having some trouble getting `dialog_simplify.py` to work on the test examples `simplify_examples.py`. I'm running the command as:

```
PYTHONPATH=$(pwd) python opendf/dialog_simplify.py -d 1 ../smcalflow
```

I was able to fix the first couple of errors but I'm now stuck on this error:
```
Traceback (most recent call last):
  File "/home/shivag5/Documents/research/comp-gen/OpenDF/opendf/dialog_simplify.py", line 183, in dialog
    bgl, ex = pre_simplify_graph(igl, d_context)
  File "/home/shivag5/Documents/research/comp-gen/OpenDF/opendf/graph/simplify_graph.py", line 87, in pre_simplify_graph
    e = recursive_pre_simplify(nd, d_context, nd, None, None)
  File "/home/shivag5/Documents/research/comp-gen/OpenDF/opendf/graph/simplify_graph.py", line 99, in recursive_pre_simplify
    e = recursive_pre_simplify(n.input_view(i), d_context, top, e,
  File "/home/shivag5/Documents/research/comp-gen/OpenDF/opendf/graph/simplify_graph.py", line 99, in recursive_pre_simplify
    e = recursive_pre_simplify(n.input_view(i), d_context, top, e,
  File "/home/shivag5/Documents/research/comp-gen/OpenDF/opendf/graph/simplify_graph.py", line 105, in recursive_pre_simplify
    m, e, mode = n.pre_simplify(top, mode, d_context)
TypeError: pre_simplify() takes 3 positional arguments but 4 were given
```

The other errors were:
1. `argparse.ArgumentError: argument --log/-l: conflicting option strings: --log, -l` because the `--log` argument is added twice.
2. `AttributeError: 'Namespace' object has no attribute 'environment'` because `parser = add_environment_option(parser)` is missing in `dialog_simplify.py` unlike in `dialog.py`.

**Comment by guimaraes-tl** [comment]
Hi Shivanshu-Gupta,

Thank you for your comment.
This function was receiving a parameter that is no longer required, it is fixed now and you should be able to run your example on this new version.

Best regards.
