### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'call_eval'

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#22]
Dear authors,

OpenDF failed to execute this dialog, which might deserve a fix:

## Dialog 75

**GUID**: `47c6ad36-cf06-4240-85ac-efd59d21390a` **OpenDF**:

 - U1: Tell me when I have something to do again
 - A1: I found 1 matching event on your calendar. It's "lunch with Maggie" on Tuesday the 19th from 1:00 to 2:00 PM.
 - U2: Anything **after that**?
 - A2: No, I didn't find any events on Tuesday the 19th after 2:00 PM.
 - U3: I thought my next event wasn't until Tuesday
 - A3: The "lunch with Maggie" on Tuesday the 19th from 1:00 to 2:00 PM.

Program:

```
 FindEvents(
    Event?(
       ) ) 
```

If the calendar is empty, OpenDF raises:

```
Traceback (most recent call last):
File "OpenDF/opendf/graph/eval.py", line 87, in recursive_eval
node.evaluate(prev_nodes, prev_goals)
File "OpenDF/opendf/graph/nodes/node.py", line 945, in evaluate
self.exec(all_nodes, goals)
File "OpenDF/opendf/applications/smcalflow/nodes/functions.py", line 1286, in exec
r.call_eval(add_goal=False)  # pedantic
AttributeError: 'NoneType' object has no attribute 'call_eval'
```

**Comment by hankcs** [comment]
I found this bug was caused by an empty event in the database. So when the stubdata.py contains no event, this line will add an event with all fields being None and this leads to the bug.

https://github.com/telepathylabsai/OpenDF/blob/f75a20eb3c0191931abc7bbf9bbd5b67be4e107d/opendf/applications/smcalflow/database.py#L1056

I'd suggest to change it to:

```
        if event_data:
            connection.execute(insert(database.EVENT_TABLE), event_data)
```

**Comment by guimaraes-tl** [comment]
It was fixed in https://github.com/telepathylabsai/OpenDF/commit/754faecc6a33de255dd429bacac7139fed382f97
