### ISSUE TITLE
Graphviz: Error: not well-formed (invalid token) in line 1 

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#24]
Dear authors,

Graphviz doesn't allow for `&` in html code. So could you help me to sanitize it?

Database has `D&D  Night`:

![Screen Shot 2022-06-21 at 5 11 01 PM](https://user-images.githubusercontent.com/5326890/174898050-ffa7ff80-973c-4e25-b641-5e00db235854.png)

Program:

```
 FindEvents(
    starts_at(
       adjustByPeriod(
          refer(
             Date?(
                ) ) ,
          toDays(
             1 ) ) ) )
```

Log:

```
Error: not well-formed (invalid token) in line 1
... <HTML>D&D  Night ...
in label of node 31=D&D  Night
Traceback (most recent call last):
File "OpenDF/venv/lib/python3.8/site-packages/graphviz/backend/execute.py", line 91, in run_check
proc.check_returncode()
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 448, in check_returncode
raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[PosixPath('dot'), '-Kdot', '-Tpdf', '-O', '93.dot']' returned non-zero exit status 1.
```

**Comment by meron-tl** [comment]
Fixed bug drawing special characters. commit 11a8e9c4.  Please try again
