### ISSUE TITLE
opendf.exceptions.python_exception.ParserException: Syntax error at `LexToken(OPEN_ARGUMENTS,'(',1,15)`

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#27]
Dear authors,

I found this very common bug that occurs in many many dialogs. So I'm wishing for a fix such that a lot of dialogs can benefit. 

Expressions:
```
CreateEvent(
    AND(
       has_subject(
          swimming ) ,
       starts_at(
          NextDOW(
             FRIDAY ) ) ) ) 

AcceptSuggestion()
```

First expression executes fine, but the second `AcceptSuggestion()` raises:

```
Traceback (most recent call last):
File "OpenDF/opendf/applications/smcalflow/nodes/functions.py", line 1409, in exec
d = Event.create_suggestion(cp, self)
File "OpenDF/opendf/applications/smcalflow/nodes/objects.py", line 904, in create_suggestion
return Event.get_event_factory().create_event_suggestion(root, parent, avoid_id)
File "OpenDF/opendf/applications/smcalflow/nodes/event_factory.py", line 784, in create_event_suggestion
self.get_suggestions_from_database(root, root.context, subj, atts, avoid_id)
File "OpenDF/opendf/applications/smcalflow/nodes/event_factory.py", line 860, in get_suggestions_from_database
selection = self.create_database_selection(root, d_context, subject, attendees_ids, ignore_event_id)
File "OpenDF/opendf/applications/smcalflow/nodes/event_factory.py", line 928, in create_database_selection
cstart = Node.get_truncated_constraint_tree(ttree, 'TimeSlot', 'DateTime', 'start')
File "OpenDF/opendf/graph/nodes/node.py", line 2504, in get_truncated_constraint_tree
r, e = Node.call_construct(sexp, d_context)
File "OpenDF/opendf/graph/nodes/node.py", line 1857, in call_construct
g, ex = construct_graph(sexp, d_context, register=register, top_only=top_only, constr_tag=constr_tag,
File "OpenDF/opendf/graph/constr_graph.py", line 91, in construct_graph
raise ex
File "OpenDF/opendf/graph/constr_graph.py", line 86, in construct_graph
prs = parse_p_expressions(sexp)
File "OpenDF/opendf/parser/pexp_parser.py", line 460, in parse_p_expressions
return parser.parse(expressions)
File "OpenDF/opendf/parser/pexp_parser.py", line 351, in parse
self.parser.parse(input=expressions, lexer=self.lexer)
File "OpenDF/venv/lib/python3.8/site-packages/ply/yacc.py", line 333, in parse
return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
File "OpenDF/venv/lib/python3.8/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
tok = call_errorfunc(self.errorfunc, errtoken, self)
File "OpenDF/venv/lib/python3.8/site-packages/ply/yacc.py", line 192, in call_errorfunc
r = errorfunc(token)
File "OpenDF/opendf/parser/pexp_parser.py", line 443, in p_error
raise ParserException(p)
opendf.exceptions.python_exception.ParserException: Syntax error at `LexToken(OPEN_ARGUMENTS,'(',1,15)`
```

**Comment by hankcs** [comment]
> Not sure about this - does this work for you? (when you put it in main_examples, dialogs[0])
> 
> 'CreateEvent(AND(has_subject(swimming ) ,starts_at(NextDOW(FRIDAY ) ) ) )', 'AcceptSuggestion()'

Thanks, this one worked. After some debugging, I found `d_context.inc_turn_num()` is required before `AcceptSuggestion`.

**Comment by meron-tl** [comment]
As a rule, to have multiple expression in one turn, they should be inside a 'do' expression. Otherwise, each expression should be a separate turn.

In this example, it makes sense to have the two expressions in separate turns.

**Comment by hankcs** [comment]
Thanks for you clarification. Closing this now.
